apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spatial-proteomics-data
  namespace: spatial-proteomics
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

